name: wm
spec-version: 0.36.0

default-extensions:
        - GeneralizedNewtypeDeriving
        - MultiParamTypeClasses
        - ScopedTypeVariables
        - OverloadedStrings
        - TypeApplications
        - FlexibleContexts
        - ConstraintKinds
        - TemplateHaskell
        - KindSignatures
        - NamedFieldPuns
        - TypeOperators
        - DeriveGeneric
        - TypeFamilies
        - LambdaCase
        - RankNTypes
        - DataKinds
        - Arrows
        - GADTs

dependencies:
        - xmonad-wallpaper
        - xmonad-contrib
        - xmonad-extras
        - containers
        - xmonad
        - base

library:
        source-dirs: .