name:                 wm
version:              0.0.0
visibility:           public
id:                   wm-0.0.0-inplace
key:                  wm-0.0.0-inplace
abi:                  inplace
exposed:              True
exposed-modules:      Main
import-dirs:
    /home/indigo/nix/wm/xmonad/dist-newstyle/build/x86_64-linux/ghc-9.12.4/wm-0.0.0/build

library-dirs:
    /home/indigo/nix/wm/xmonad/dist-newstyle/build/x86_64-linux/ghc-9.12.4/wm-0.0.0/build

library-dirs-static:
    /home/indigo/nix/wm/xmonad/dist-newstyle/build/x86_64-linux/ghc-9.12.4/wm-0.0.0/build

dynamic-library-dirs:
    /home/indigo/nix/wm/xmonad/dist-newstyle/build/x86_64-linux/ghc-9.12.4/wm-0.0.0/build

data-dir:             /home/indigo/nix/wm/xmonad/.
hs-libraries:         HSwm-0.0.0-inplace
depends:
    base-4.21.2.0-216a
    xmonad-0.18.1-7194b3383c522d65ccfd7cf0abad7170e00d108bc7d403884e69bd8355251b83

haddock-interfaces:
    /home/indigo/nix/wm/xmonad/dist-newstyle/build/x86_64-linux/ghc-9.12.4/wm-0.0.0/doc/html/wm/wm.haddock

haddock-html:
    /home/indigo/nix/wm/xmonad/dist-newstyle/build/x86_64-linux/ghc-9.12.4/wm-0.0.0/doc/html/wm
